#!/usr/bin/env python3
"""The OCHA Humanitarian Icons the film uses, inlined and recolourable.

    python3 assets/build/icons.py
Writes assets/build/film/icons.js (window.ICONS = {name: "<svg …>"}).

List the icons in NAMES (their file names, Hyphen-Case: "People-in-need"; find names with the
humanitarian-icons skill). Official icons only: never draw one. Each icon's OCHA blue becomes
currentColor, so CSS `color` sets it (red for a crisis, blue once answered); other fills (white
details) are kept. Class-based <style> blocks are inlined, because several inline SVGs sharing
`.cls-1` rules on one page would recolour each other.

Source: the BDU's local copy of the icon set if it is on this Mac (Dropbox), otherwise the public
repository (jsDelivr CDN). OCHA_ICONS=/path/to/svg overrides both.
"""
import json, os, re, urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
NAMES = [   # the demo's; the SG film used 49
    "Earthquake", "Flood", "Cyclone", "Help", "Time",
    "Person-1", "Person-2", "Children", "Elderly", "Pregnant", "Infant", "People-with-physical-impairments",
]
CDN = "https://cdn.jsdelivr.net/gh/UN-OCHA/humanitarian-icons-2026-BDU@main/svg/{}.svg"


def local_set():
    if os.environ.get("OCHA_ICONS"):
        return Path(os.environ["OCHA_ICONS"]).expanduser()
    hits = sorted(Path.home().glob("OCHA DMU Dropbox/*/Design/Humanitarian_Icons/v2/Humanitarian_Icons_2026/humanitarian-icons-2026/svg"))
    return hits[0] if hits else None


def read_icon(name, folder):
    if folder:
        f = folder / f"{name}.svg"
        if f.exists() and f.stat().st_size:   # 0 bytes = a Dropbox online-only placeholder: use the CDN
            return f.read_text(encoding="utf-8")
    with urllib.request.urlopen(CDN.format(name), timeout=20) as r:
        return r.read().decode("utf-8")


folder, out = local_set(), {}
for n in NAMES:
    try:
        s = read_icon(n, folder)
    except Exception as e:
        raise SystemExit(f"Icon '{n}' not found locally or on the CDN ({e}). Check its name with the humanitarian-icons skill.")
    styles = dict(re.findall(r"\.([\w-]+)\s*\{\s*fill:\s*([^;}]+);?\s*\}", s))
    s = re.sub(r"<defs>.*?</defs>|<title>.*?</title>|<\?xml.*?\?>", "", s, flags=re.S)
    s = re.sub(r'class="([\w-]+)"', lambda m: f'fill="{styles.get(m.group(1), "currentColor")}"', s)
    s = re.sub(r"#009edb", "currentColor", s, flags=re.I)
    s = s.replace("<svg ", '<svg aria-hidden="true" focusable="false" ', 1)
    out[n] = s.strip()
(HERE / "film/icons.js").write_text("// Generated by assets/build/icons.py — do not edit by hand.\nwindow.ICONS = "
                                   + json.dumps(out, ensure_ascii=False) + ";\n", encoding="utf-8")
print(f"{len(out)} icons from {folder or 'the CDN'} · fills used:", sorted({f for v in out.values() for f in re.findall(r'fill="([^"]+)"', v)}))
