#!/usr/bin/env python3
"""The film's timeline, built from the voiceover's measured word timings.

    python3 assets/build/timeline.py
Reads  assets/voice/voiceover_timings.json   (word_timings.py; the kit ships a demo one)
Writes assets/build/film/timeline.js          (window.TIMELINE, loaded by the film page)
       assets/build/timeline.json             (the same data, for the sound tools and the review tool)

Everything in the film is cued from these times (W(line)[word].start), never from typed seconds, so
when the voice or the pacing changes, re-run this and the whole film moves with it.

The voice can be placed in BLOCKS, so the film breathes where the script asks for it: a beat after a
big moment, a held pause before the sign-off. Set the numbers below and re-run.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]          # the job folder (this file lives in <job>/assets/build/)
T = json.loads((ROOT / "assets/voice/voiceover_timings.json").read_text(encoding="utf-8"))
lines = {r["line"]: r for r in T["lines"]}

# ---- the film's pacing: change these, re-run, and every scene moves with them ----
LEAD_IN = 0.25      # picture before the recording starts: the film opens right as the words start (SG film, review round 1: 1.5 s was too long)
SCENE_LEAD = 0.4    # a scene's picture changes this long before its first word
END_HOLD = 1.0      # after the last word, then the black sheet starts (SG round 2: "you can end the video here")
ENDING = 1.1        # the black sheet wiping in (0.55 s) and a breath of black
SCENES = [          # id, title, first line, last line — every line in exactly one scene, in order
    (1, "Questions", 1, 1),
    (2, "Answers", 2, 2),
]
# BEATS: {line: seconds} — before this line, hold the picture this long after the previous line ends
# (measured to the next scene's start). Its voice block, and everything after it, moves later.
# The SG film had two: a 1.2 s beat after the tool's name, a 0.9 s hold after "saves lives".
BEATS = {}

# ---- from here on, nothing to change ----
first, last = min(lines), max(lines)
offset, off = {}, LEAD_IN   # film time = the recording's own time + its block's offset (voice_track.py places it so)
blocks = []
for n in sorted(lines):
    if n in BEATS and n != first:
        natural = lines[n]["start"] - lines[n - 1]["end"]
        off += BEATS[n] + SCENE_LEAD - natural
    if not blocks or n in BEATS:
        blocks.append([n, n, off])
    blocks[-1][1] = n
    offset[n] = off

placed = [{"line": n, "text": lines[n]["text"], "start": round(lines[n]["start"] + offset[n], 2),
           "end": round(lines[n]["end"] + offset[n], 2)} for n in sorted(lines)]
p = {r["line"]: r for r in placed}
covered = sorted(n for _, _, a, b in SCENES for n in range(a, b + 1))
if covered != sorted(lines):
    raise SystemExit(f"SCENES must cover every line once, in order: they cover {covered}, the voice has {sorted(lines)}")

scenes = []
for i, (sid, title, a, b) in enumerate(SCENES):
    start = 0.0 if i == 0 else round(p[a]["start"] - SCENE_LEAD, 2)
    scenes.append({"id": sid, "title": title, "start": start, "first_line": a, "last_line": b})
for i, s in enumerate(scenes):
    s["end"] = scenes[i + 1]["start"] if i + 1 < len(scenes) else round(p[last]["end"] + END_HOLD, 2)
ending_start = scenes[-1]["end"]
scenes.append({"id": len(SCENES) + 1, "title": "Swipe to black", "start": ending_start,
               "end": round(ending_start + ENDING, 2), "first_line": None, "last_line": None})
duration = scenes[-1]["end"]

data = {"duration": duration, "voice_blocks": [{"lines": [a, b], "offset": round(o, 3)} for a, b, o in blocks],
        "scenes": scenes, "lines": placed, "words": [
            {**w, "start": round(w["start"] + offset[w["line"]], 3), "end": round(w["end"] + offset[w["line"]], 3)}
            for w in T["words"]]}
(ROOT / "assets/build/timeline.json").write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8")
(ROOT / "assets/build/film/timeline.js").write_text(
    "// Generated by assets/build/timeline.py — do not edit by hand.\nwindow.TIMELINE = "
    + json.dumps(data, ensure_ascii=False) + ";\n", encoding="utf-8")

for s in scenes:
    print(f'{s["id"]}  {s["start"]:6.2f}–{s["end"]:6.2f}  ({s["end"] - s["start"]:4.1f}s)  {s["title"]}')
print(f"film {duration:.2f}s = {int(duration // 60)}:{duration % 60:04.1f} · voice in {len(blocks)} block(s)")
